### PR TITLE
Database implementation

### LINKED ISSUE #24: Data base set up
4.6 As a user I want the time for the races I've completed to be stored and showcased so I can compare and brag about it to my friends.

Acceptance criteria: User race times is stored and displayed in the software

FR: 1.18

### LINKED ISSUE #50: Database frontend setup
Database backend setup has been added in database branch. Frontend implementation required for showing race times as well as showing the leaderboard.

Users should be able to 'sign in' by giving a username, which will then be saved at the end of a race with their times. - The sign-in is implemented in the login issue #79 and

### PR DESCRIPTION
**Pull request by VernitaJ**
The backend implementation configured to an online database. The frontend implementation for leaderboard is in this branch, and the race times implementation will be incorporated in sprint3.

### CODE REVIEW

**Review by MrJonte — APPROVED** [review]
I dont know about all the 2.5k changed files. assume it is npm install updates

**Review by platisd — DISMISSED** [review]
[Should I check in my node modules into git?](http://manpages.ubuntu.com/manpages/bionic/man7/npm-faq.7.html#should%20i%20check%20my%20%3Ccode%3Enode_modules%3C/code%3E%20folder%20into%20git?)

**Comment by VernitaJ** [comment]
> I dont know about all the 2.5k changed files. assume it is npm install updates

Damn, you're right. It's supposed to be in the git.ignore file, I'll go add it.

**Comment by VernitaJ** [comment]
> [Should I check in my node modules into git?](http://manpages.ubuntu.com/manpages/bionic/man7/npm-faq.7.html#should%20i%20check%20my%20%3Ccode%3Enode_modules%3C/code%3E%20folder%20into%20git?)

Useful, thank you. Have removed the node_modules folder.

**Pull request merged**
