### PR TITLE
Create a new car model and map for SMCE

### LINKED ISSUE #23: Customize Environment
Customize environment with GODOT to fit our vision for the smartcar.

### LINKED ISSUE #40: Create new building models; Current models are obsolete.
Building models are currently too repetitive. We need new models with more "dynamic" looking scenes.

### LINKED ISSUE #42: New car models
Current car model is far too basic, and is incompatible with multiplayer  ( see #31 ).

Shall we use multiple models? Or just one model with multiple textures? If it's the latter, please create a new issue for the textures.

### PR DESCRIPTION
**Pull request by drakeaxelrod**
Merged the RayCar with a opensource godot model. Uses all the same
attachments that RayCar uses, this means that to run the new model you
need access to the uncompiled project as far as I am aware. duplicated
the code for the car and spring however into our new model so that we
can tweak values unrelated to the sensors and attachments.

### CODE REVIEW

**Review by worldisyoursdude — APPROVED** [review]
Great work! Everything tested is functional, and the wheels' movement was a surprise I didn't expect. 10/10 work, big guy!

**Review by Axel-J-L — APPROVED** [review]
Great job. Felt good getting in the new car, making it more visibly realistic. Thanks for the help with this.

**Review by worldisyoursdude — CHANGES_REQUESTED** [review]
Don't merge this. The race track map, while fully functional along with the new car models, isn't part of the issue at hand. Please push the map to the other issue (#23).

**Comment by klarasve** [comment]
> Don't merge this. The race track map, while fully functional along with the new car models, isn't part of the issue at hand. Please push the map to the other issue (#23).

You can link multiple issues to a merge request so this merge is fine.

**Comment by VernitaJ** [comment]
As @klarasve mentioned above, both of the issues pertaining to this PR are now linked, which means we can merge this PR.
@TheEyass Mark your request as solved so we can merge.

**Review by worldisyoursdude — APPROVED** [review]
In that case,

Mr Gorbachev, merge this request.

**Pull request merged**
